sudo: false
language: go
go:
  - 1.5
script: cd src/github.com/sol1/flapjack-icinga2/ && go build -v && go test -v && cd ../../../..
services:
- redis-server
install:
- go get gopkg.in/alecthomas/kingpin.v2
- go get github.com/garyburd/redigo/redis